[package]
name = "stupid_vm"
version = "0.1.0"
authors = ["bmartynov <boriska91m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.6.3"