#[derive(Debug, PartialEq)]
pub enum Instruction {
    IGL,
    HLT,
    RET,
    JMP { dst: usize },
    JMPE { dst: usize },
    JMPNE { dst: usize },
    CALL { dst: usize },
    CLOOP { count: usize },
    LOOP { dst: usize },
    INC { r: usize },
    LOAD { rd: usize, value: i32 },
    ADD { rd: usize, rl: usize, rh: usize },
    SUB { rd: usize, rl: usize, rh: usize },
    MUL { rd: usize, rl: usize, rh: usize },
    DIV { rd: usize, rl: usize, rh: usize },
    EQ { rl: usize, rh: usize },
    NEQ { rl: usize, rh: usize },
    GTE { rl: usize, rh: usize },
    LTE { rl: usize, rh: usize },
    LT { rl: usize, rh: usize },
    GT { rl: usize, rh: usize },
}
